# Generated by Django 2.1.5 on 2019-06-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0012_auto_20170606_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='value',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orgs.Org'),
        ),
    ]
