# Generated by Django 2.1.5 on 2019-06-08 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtime', '0007_auto_20170228_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimetransfer',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='The channel that this airtime is relating to', null=True, on_delete=django.db.models.deletion.PROTECT, to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='airtimetransfer',
            name='contact',
            field=models.ForeignKey(help_text='The contact that this airtime is sent to', on_delete=django.db.models.deletion.PROTECT, to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='airtimetransfer',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='airtime_airtimetransfer_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airtimetransfer',
            name='data',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='airtimetransfer',
            name='message',
            field=models.CharField(blank=True, help_text='A message describing the end status, error messages go here', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='airtimetransfer',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='airtime_airtimetransfer_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airtimetransfer',
            name='org',
            field=models.ForeignKey(help_text='The organization that this airtime was triggered for', on_delete=django.db.models.deletion.PROTECT, to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='airtimetransfer',
            name='response',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='airtimetransfer',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Success'), ('F', 'Failed')], default='P', help_text='The state this event is currently in', max_length=1),
        ),
    ]
