# Generated by Django 2.1.5 on 2019-06-08 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0038_creditalert_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditalert',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='orgs_creditalert_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditalert',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='orgs_creditalert_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditalert',
            name='org',
            field=models.ForeignKey(help_text='The organization this alert was triggered for', on_delete=django.db.models.deletion.PROTECT, to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='beneficiary',
            field=models.ForeignKey(help_text='Optional topup that was allocated with these credits', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='orgs.TopUp'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debits_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debit',
            name='topup',
            field=models.ForeignKey(help_text='The topup these credits are applied against', on_delete=django.db.models.deletion.PROTECT, related_name='debits', to='orgs.TopUp'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='orgs_invitation_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='orgs_invitation_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='org',
            field=models.ForeignKey(help_text='The organization to which the account is invited to view', on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='orgs.Org', verbose_name='Org'),
        ),
        migrations.AlterField(
            model_name='language',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='orgs_language_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='language',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='orgs_language_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='language',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='languages', to='orgs.Org', verbose_name='Org'),
        ),
        migrations.AlterField(
            model_name='org',
            name='country',
            field=models.ForeignKey(blank=True, help_text='The country this organization should map results for.', null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.AdminBoundary'),
        ),
        migrations.AlterField(
            model_name='org',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='orgs_org_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='org',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='orgs_org_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='org',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent org that manages this org', null=True, on_delete=django.db.models.deletion.PROTECT, to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='org',
            name='slug',
            field=models.SlugField(blank=True, error_messages={'unique': 'This slug is not available'}, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='topup',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='orgs_topup_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topup',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='orgs_topup_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topup',
            name='org',
            field=models.ForeignKey(help_text='The organization that was toppped up', on_delete=django.db.models.deletion.PROTECT, related_name='topups', to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='topupcredits',
            name='topup',
            field=models.ForeignKey(help_text='The topup these credits are being used against', on_delete=django.db.models.deletion.PROTECT, to='orgs.TopUp'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
