# Generated by Django 2.1.5 on 2019-06-08 15:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import temba.channels.models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0080_fix_sql_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='channel',
            field=models.ForeignKey(help_text='The channel that this alert is for', on_delete=django.db.models.deletion.PROTECT, to='channels.Channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='channels_alert_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='channels_alert_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='sync_event',
            field=models.ForeignKey(help_text='The sync event that caused this alert to be sent (if any)', null=True, on_delete=django.db.models.deletion.PROTECT, to='channels.SyncEvent', verbose_name='Sync Event'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='channels_channel_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='channels_channel_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Organization using this channel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='orgs.Org', verbose_name='Org'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The channel this channel is working on behalf of', null=True, on_delete=django.db.models.deletion.PROTECT, to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='schemes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), default=temba.channels.models._get_default_channel_scheme, help_text='The URN schemes this channel supports', size=None, verbose_name='URN Schemes'),
        ),
        migrations.AlterField(
            model_name='channelcount',
            name='channel',
            field=models.ForeignKey(help_text='The channel this is a daily summary count for', on_delete=django.db.models.deletion.PROTECT, to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='channelevent',
            name='channel',
            field=models.ForeignKey(help_text='The channel on which this event took place', on_delete=django.db.models.deletion.PROTECT, to='channels.Channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='channelevent',
            name='contact',
            field=models.ForeignKey(help_text='The contact associated with this event', on_delete=django.db.models.deletion.PROTECT, related_name='channel_events', to='contacts.Contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='channelevent',
            name='contact_urn',
            field=models.ForeignKey(help_text='The contact URN associated with this event', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_events', to='contacts.ContactURN', verbose_name='URN'),
        ),
        migrations.AlterField(
            model_name='channelevent',
            name='org',
            field=models.ForeignKey(help_text='The org this event is connected to', on_delete=django.db.models.deletion.PROTECT, to='orgs.Org', verbose_name='Org'),
        ),
        migrations.AlterField(
            model_name='channellog',
            name='channel',
            field=models.ForeignKey(help_text='The channel the message was sent on', on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='channellog',
            name='connection',
            field=models.ForeignKey(help_text='The channel session for this log', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_logs', to='channels.ChannelSession'),
        ),
        migrations.AlterField(
            model_name='channellog',
            name='msg',
            field=models.ForeignKey(help_text='The message that was sent', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_logs', to='msgs.Msg'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='channel',
            field=models.ForeignKey(help_text='The channel that created this session', on_delete=django.db.models.deletion.PROTECT, to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='contact',
            field=models.ForeignKey(help_text='Who this session is with', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='contact_urn',
            field=models.ForeignKey(help_text='The URN this session is communicating with', on_delete=django.db.models.deletion.PROTECT, to='contacts.ContactURN', verbose_name='Contact URN'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='channels_channelsession_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='channels_channelsession_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='org',
            field=models.ForeignKey(help_text='The organization this session belongs to', on_delete=django.db.models.deletion.PROTECT, to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='syncevent',
            name='channel',
            field=models.ForeignKey(help_text='The channel that synced to the server', on_delete=django.db.models.deletion.PROTECT, to='channels.Channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='syncevent',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='channels_syncevent_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='syncevent',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='channels_syncevent_modifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
