# Generated by Django 2.1.5 on 2019-07-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0081_auto_20190608_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsession',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('Q', 'Queued'), ('W', 'Wired'), ('R', 'Ringing'), ('I', 'In Progress'), ('D', 'Complete'), ('B', 'Busy'), ('F', 'Failed'), ('N', 'No Answer'), ('C', 'Canceled'), ('X', 'Interrupted'), ('T', 'Triggered'), ('A', 'Initiated'), ('E', 'Ending')], default='P', help_text='The status of this session', max_length=1),
        ),
    ]
