# Generated by Django 2.1.5 on 2019-06-08 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0137_flowstart_embedded_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='flows.FlowRun'),
        ),
        migrations.AlterField(
            model_name='actionset',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_sets', to='flows.Flow'),
        ),
        migrations.AlterField(
            model_name='exportflowimagestask',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='flows_exportflowimagestask_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportflowimagestask',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='flows_exportflowimagestask_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportflowimagestask',
            name='org',
            field=models.ForeignKey(help_text='The organization of the user.', on_delete=django.db.models.deletion.PROTECT, related_name='exportflowimagestasks', to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='exportflowresultstask',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='flows_exportflowresultstask_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportflowresultstask',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='flows_exportflowresultstask_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportflowresultstask',
            name='org',
            field=models.ForeignKey(help_text='The organization of the user.', on_delete=django.db.models.deletion.PROTECT, related_name='exportflowresultstasks', to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='flows_flow_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flow',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='flows_flow_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flow',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flows', to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='saved_by',
            field=models.ForeignKey(help_text='The user which last saved this flow', on_delete=django.db.models.deletion.PROTECT, related_name='flow_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flowcategorycount',
            name='flow',
            field=models.ForeignKey(help_text='The flow the result belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='category_counts', to='flows.Flow'),
        ),
        migrations.AlterField(
            model_name='flowimage',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flow_images', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='flowimage',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='flows_flowimage_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flowimage',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flow_images', to='flows.Flow'),
        ),
        migrations.AlterField(
            model_name='flowimage',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='flows_flowimage_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flowimage',
            name='org',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='flow_images', to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='flowlabel',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='flowlabel',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='flows.FlowLabel', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='flownodecount',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flows.Flow'),
        ),
        migrations.AlterField(
            model_name='flowpathcount',
            name='flow',
            field=models.ForeignKey(help_text='The flow where the activity occurred', on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='flows.Flow'),
        ),
        migrations.AlterField(
            model_name='flowpathrecentmessage',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recent_messages', to='flows.FlowRun'),
        ),
        migrations.AlterField(
            model_name='flowrevision',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='flows_flowrevision_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flowrevision',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='flows.Flow'),
        ),
        migrations.AlterField(
            model_name='flowrevision',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='flows_flowrevision_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flowrun',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='The session that handled this flow run, only for voice flows', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='channels.ChannelSession'),
        ),
        migrations.AlterField(
            model_name='flowrun',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='flowrun',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='flows.Flow'),
        ),
        migrations.AlterField(
            model_name='flowrun',
            name='org',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='flowrun',
            name='parent',
            field=models.ForeignKey(help_text='The parent run that triggered us', null=True, on_delete=django.db.models.deletion.PROTECT, to='flows.FlowRun'),
        ),
        migrations.AlterField(
            model_name='flowrun',
            name='session',
            field=models.ForeignKey(help_text='The session that handled this flow run, only for voice flows', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='flows.FlowSession'),
        ),
        migrations.AlterField(
            model_name='flowrun',
            name='start',
            field=models.ForeignKey(blank=True, help_text='The FlowStart objects that started this run', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='flows.FlowStart'),
        ),
        migrations.AlterField(
            model_name='flowrun',
            name='submitted_by',
            field=models.ForeignKey(help_text='The user which submitted this flow run', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flowruncount',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='flows.Flow'),
        ),
        migrations.AlterField(
            model_name='flowsession',
            name='connection',
            field=models.OneToOneField(help_text='The channel connection used for flow sessions over IVR or USSD', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session', to='channels.ChannelSession'),
        ),
        migrations.AlterField(
            model_name='flowsession',
            name='contact',
            field=models.ForeignKey(help_text='The contact that this session is with', on_delete=django.db.models.deletion.PROTECT, to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='flowsession',
            name='org',
            field=models.ForeignKey(help_text='The organization this session belongs to', on_delete=django.db.models.deletion.PROTECT, to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='flowstart',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='flows_flowstart_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flowstart',
            name='flow',
            field=models.ForeignKey(help_text='The flow that is being started', on_delete=django.db.models.deletion.PROTECT, related_name='starts', to='flows.Flow'),
        ),
        migrations.AlterField(
            model_name='flowstart',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='flows_flowstart_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flowstep',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flow_steps', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='flowstep',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='flows.FlowRun'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_sets', to='flows.Flow'),
        ),
    ]
