# Generated by Django 2.1.5 on 2019-06-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0138_auto_20190608_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowrun',
            name='delete_reason',
            field=models.CharField(choices=[('A', 'Archive delete'), ('U', 'User delete')], help_text='Why the run is being deleted', max_length=1, null=True),
        ),
    ]
