# Generated by Django 2.1.5 on 2019-06-08 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0072_contact_salesforce_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='contacts_contact_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='contacts_contact_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='org',
            field=models.ForeignKey(help_text='The organization that this contact belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='org_contacts', to='orgs.Org', verbose_name='Org'),
        ),
        migrations.AlterField(
            model_name='contactfield',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='contacts_contactfield_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactfield',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='contacts_contactfield_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactfield',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactfields', to='orgs.Org', verbose_name='Org'),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='contacts_contactgroup_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='import_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='csv_imports.ImportTask'),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='contacts_contactgroup_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='org',
            field=models.ForeignKey(help_text='The organization this group is part of', on_delete=django.db.models.deletion.PROTECT, related_name='all_groups', to='orgs.Org', verbose_name='Org'),
        ),
        migrations.AlterField(
            model_name='contactgroupcount',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='contacts.ContactGroup'),
        ),
        migrations.AlterField(
            model_name='contacturn',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='The preferred channel for this URN', null=True, on_delete=django.db.models.deletion.PROTECT, to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='contacturn',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='The contact that this URN is for, can be null', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='urns', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='contacturn',
            name='org',
            field=models.ForeignKey(help_text='The organization for this URN, can be null', on_delete=django.db.models.deletion.PROTECT, to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='exportcontactstask',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='contacts_exportcontactstask_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportcontactstask',
            name='group',
            field=models.ForeignKey(help_text='The unique group to export', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='contacts.ContactGroup'),
        ),
        migrations.AlterField(
            model_name='exportcontactstask',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='contacts_exportcontactstask_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportcontactstask',
            name='org',
            field=models.ForeignKey(help_text='The organization of the user.', on_delete=django.db.models.deletion.PROTECT, related_name='exportcontactstasks', to='orgs.Org'),
        ),
    ]
