# Generated by Django 2.1.5 on 2019-06-08 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_exportlinkstask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportlinkstask',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='links_exportlinkstask_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportlinkstask',
            name='link',
            field=models.ForeignKey(help_text='The trackable link to export', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='links.Link'),
        ),
        migrations.AlterField(
            model_name='exportlinkstask',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='links_exportlinkstask_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportlinkstask',
            name='org',
            field=models.ForeignKey(help_text='The organization of the user.', on_delete=django.db.models.deletion.PROTECT, related_name='exportlinkstasks', to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='link',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='links_link_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='links_link_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='linkcontacts',
            name='contact',
            field=models.ForeignKey(help_text='The users which clicked on this link', on_delete=django.db.models.deletion.PROTECT, related_name='contact_links', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='linkcontacts',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='links_linkcontacts_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkcontacts',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='links.Link'),
        ),
        migrations.AlterField(
            model_name='linkcontacts',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='links_linkcontacts_modifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
