# Generated by Django 2.1.5 on 2019-06-08 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0011_trigger_embedded_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='channel',
            field=models.ForeignKey(help_text='The associated channel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggers', to='channels.Channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='triggers_trigger_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='flow',
            field=models.ForeignKey(help_text='Which flow will be started', on_delete=django.db.models.deletion.PROTECT, related_name='triggers', to='flows.Flow', verbose_name='Flow'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='triggers_trigger_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='org',
            field=models.ForeignKey(help_text='The organization this trigger belongs to', on_delete=django.db.models.deletion.PROTECT, to='orgs.Org', verbose_name='Org'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='schedule',
            field=models.OneToOneField(blank=True, help_text='Our recurring schedule', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trigger', to='schedules.Schedule', verbose_name='Schedule'),
        ),
    ]
